import { RecipeArt } from "@/components/RecipeArt";
import photoManifest from "@/data/recipe_photos.json";
import type { FlatRecipe } from "@/lib/recipes";
import { useState } from "react";

// The manifest is regenerated by scripts/generate_recipe_images.py (a sorted
// list of slugs whose photo exists under public/images/recipes/). Validate at
// runtime so a malformed manifest degrades to SVG art instead of misbehaving.
const manifestValues: unknown = photoManifest;
const photoSlugs = new Set<string>(
  Array.isArray(manifestValues) ? manifestValues.filter((s): s is string => typeof s === "string") : [],
);

interface RecipePhotoProps {
  recipe: Pick<FlatRecipe, "name" | "slug" | "ingredients" | "category">;
  variant: "card" | "hero";
  className?: string;
}

/**
 * AI-generated photo when one exists for the recipe, falling back to the
 * deterministic ingredient-driven SVG art otherwise (and on load errors).
 * With an empty manifest this renders exactly what RecipeArt rendered —
 * no requests are made for photos that don't exist.
 */
export function RecipePhoto({ recipe, variant, className }: RecipePhotoProps) {
  // Track WHICH slug failed so a reused component instance doesn't carry a
  // stale failure across route changes to a different recipe.
  const [failedSlug, setFailedSlug] = useState<string | null>(null);

  if (failedSlug === recipe.slug || !photoSlugs.has(recipe.slug)) {
    return <RecipeArt recipe={recipe} variant={variant} className={className} />;
  }

  return (
    <img
      src={`/images/recipes/${recipe.slug}.jpg`}
      alt={recipe.name}
      loading="lazy"
      className={
        className ?? (variant === "hero" ? "h-48 w-full object-cover" : "aspect-[16/9] w-full object-cover")
      }
      onError={() => setFailedSlug(recipe.slug)}
    />
  );
}
