import { RecipeArt } from "@/components/RecipeArt";
import photoManifest from "@/data/recipe_photos.json";
import type { FlatRecipe } from "@/lib/recipes";
import { useState } from "react";

// Boundary cast: the manifest is regenerated by scripts/generate_recipe_images.py
// (a sorted list of slugs whose photo exists under public/images/recipes/).
const photoSlugs = new Set<string>(photoManifest as unknown as string[]);

interface RecipePhotoProps {
  recipe: Pick<FlatRecipe, "name" | "slug" | "ingredients" | "category">;
  variant: "card" | "hero";
  className?: string;
}

/**
 * AI-generated photo when one exists for the recipe, falling back to the
 * deterministic ingredient-driven SVG art otherwise (and on load errors).
 * With an empty manifest this renders exactly what RecipeArt rendered —
 * no requests are made for photos that don't exist.
 */
export function RecipePhoto({ recipe, variant, className }: RecipePhotoProps) {
  const [failed, setFailed] = useState(false);

  if (failed || !photoSlugs.has(recipe.slug)) {
    return <RecipeArt recipe={recipe} variant={variant} className={className} />;
  }

  return (
    <img
      src={`/images/recipes/${recipe.slug}.jpg`}
      alt={recipe.name}
      loading="lazy"
      className={
        className ?? (variant === "hero" ? "h-48 w-full object-cover" : "aspect-[16/9] w-full object-cover")
      }
      onError={() => setFailed(true)}
    />
  );
}
